CREATE OR REPLACE FILE FORMAT MY_DB.PUBLIC.MY_PARQUET_FORMAT
  TYPE = PARQUET;

CREATE OR REPLACE STAGE MY_DB.PUBLIC.MY_CURATED_STAGE
  STORAGE_INTEGRATION = MY_S3_INT
  URL = 's3://ify-eso-test-bucket/curated/hcp_interactions/'
  FILE_FORMAT = MY_DB.PUBLIC.MY_PARQUET_FORMAT;