-- V2: Create curated table
CREATE OR REPLACE TABLE MY_DB.PUBLIC.HCP_INTERACTIONS_CURATED (
  HCP_ID STRING,
  REP_ID STRING,
  INTERACTION_TYPE STRING,
  INTERACTION_TS STRING,
  NOTES STRING,
  INGEST_TS STRING,
  INTERACTION_TIME TIMESTAMP_NTZ,
  INGESTION_TIME TIMESTAMP_NTZ,
  CLEANED_INTERACTION_TYPE STRING,
  IS_DUPLICATE_FLAG NUMBER,
  ETL_LOADED_AT TIMESTAMP_NTZ,
  SOURCE_FILE_PATH STRING
);

COPY INTO MY_DB.PUBLIC.HCP_INTERACTIONS_CURATED
FROM @MY_DB.PUBLIC.MY_CURATED_STAGE
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FORCE = TRUE;