-- V3: Create final table
CREATE OR REPLACE TABLE MY_DB.PUBLIC.HCP_INTERACTIONS_FINAL AS
SELECT *
FROM MY_DB.PUBLIC.HCP_INTERACTIONS_CURATED
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY HCP_ID, REP_ID, CLEANED_INTERACTION_TYPE, INTERACTION_TIME
    ORDER BY ETL_LOADED_AT DESC, INGESTION_TIME DESC
) = 1;