-- V4: Create views
CREATE OR REPLACE VIEW MY_DB.PUBLIC.VW_HCP_INTERACTIONS_KPI AS
SELECT
    DATE_TRUNC('MONTH', INTERACTION_TIME) AS INTERACTION_MONTH,
    COUNT(*) AS TOTAL_INTERACTIONS,
    COUNT(DISTINCT HCP_ID) AS UNIQUE_HCPS,
    COUNT(DISTINCT REP_ID) AS UNIQUE_REPS,
    SUM(CASE WHEN CLEANED_INTERACTION_TYPE = 'Call' THEN 1 ELSE 0 END) AS CALL_INTERACTIONS,
    SUM(CASE WHEN CLEANED_INTERACTION_TYPE = 'Email' THEN 1 ELSE 0 END) AS EMAIL_INTERACTIONS,
    SUM(CASE WHEN CLEANED_INTERACTION_TYPE = 'Meeting' THEN 1 ELSE 0 END) AS MEETING_INTERACTIONS
FROM MY_DB.PUBLIC.HCP_INTERACTIONS_FINAL
WHERE INTERACTION_TIME IS NOT NULL
GROUP BY 1;