name: Deploy Snowflake SQL

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Snowflake CLI
        uses: snowflakedb/snowflake-cli-action@v2.0.2
        with:
          cli-version: "3.16.0"

      - name: Check Snowflake CLI
        run: snow --version

      - name: Run Snowflake SQL files
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: MY_DB
          SNOWFLAKE_SCHEMA: PUBLIC
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
        run: |
          snow sql -f snowflake/V1__create_stage_and_file_format.sql
          snow sql -f snowflake/V2__create_curated_table.sql
          snow sql -f snowflake/V3__create_final_table.sql
          snow sql -f snowflake/V4__create_views.sql